In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
5    15728773    Male   27            58000          0
6    15598044  Female   27            84000          0
7    15694829  Female   32           150000          1
8    15600575    Male   25            33000          0
9    15727311  Female   35            65000          0
10   15570769  Female   26            80000          0
11   15606274  Female   26            52000          0
12   15746139    Male   20            86000          0
13   15704987    Male   32            18000          0
14   15628972    Male   18            82000          0
15   15697686    Male   29            80000          0
16   15733883    Male   47            25000          1
17   15617482    Male   45            26000          1
18   15704583    Male   46            28000          1
19   15621083  Female   48            29000          1
20   15649487    Male   45            22000          1
21   15736760  Female   47            49000          1
22   15714658    Male   48            41000          1
23   15599081  Female   45            22000          1
24   15705113    Male   46            23000          1
25   15631159    Male   47            20000          1
26   15792818    Male   49            28000          1
27   15633531  Female   47            30000          1
28   15744529    Male   29            43000          0
29   15669656    Male   31            18000          0
..        ...     ...  ...              ...        ...
370  15611430  Female   60            46000          1
371  15774744    Male   60            83000          1
372  15629885  Female   39            73000          0
373  15708791    Male   59           130000          1
374  15793890  Female   37            80000          0
375  15646091  Female   46            32000          1
376  15596984  Female   46            74000          0
377  15800215  Female   42            53000          0
378  15577806    Male   41            87000          1
379  15749381  Female   58            23000          1
380  15683758    Male   42            64000          0
381  15670615    Male   48            33000          1
382  15715622  Female   44           139000          1
383  15707634    Male   49            28000          1
384  15806901  Female   57            33000          1
385  15775335    Male   56            60000          1
386  15724150  Female   49            39000          1
387  15627220    Male   39            71000          0
388  15672330    Male   47            34000          1
389  15668521  Female   48            35000          1
390  15807837    Male   48            33000          1
391  15592570    Male   47            23000          1
392  15748589  Female   45            45000          1
393  15635893    Male   60            42000          1
394  15757632  Female   39            59000          0
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [2]:
X=dataset.iloc[:,2:4]
Y=dataset.iloc[:,4:5]

In [3]:
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X=sc_X.fit_transform(X)

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.10,random_state=20)
print(X_train)

[[-0.25358736 -0.75592482]
 [-0.25358736  0.21311545]
 [ 1.94321462 -1.37258681]
 [ 2.13424088 -0.69719511]
 [ 1.08359645  2.09246627]
 [-0.15807423 -0.52100597]
 [-0.15807423 -0.46227625]
 [-0.54012675  1.47580428]
 [-0.0625611   2.18056084]
 [-0.15807423  2.18056084]
 [-1.87731056  0.35993973]
 [ 1.46564897 -1.04957339]
 [ 1.94321462  0.74168287]
 [-0.82666613  0.15438573]
 [ 0.31949142 -0.52100597]
 [ 1.5611621  -1.28449224]
 [ 0.22397829 -0.37418169]
 [-1.20871865  0.50676401]
 [ 0.79705706  0.53612887]
 [ 1.46564897  0.06629116]
 [ 1.5611621   0.00756145]
 [ 0.22397829  0.03692631]
 [-1.78179743 -1.43131652]
 [-0.25358736  0.62422344]
 [ 0.70154394 -0.72655996]
 [-0.0625611   0.06629116]
 [ 0.22397829  2.12183112]
 [ 0.31949142  0.06629116]
 [ 0.60603081 -0.9027491 ]
 [-0.0625611   0.12502088]
 [-0.15807423  1.65199342]
 [-0.0625611   0.27184516]
 [ 0.03295203 -0.31545197]
 [ 0.51051768  1.24088543]
 [-1.87731056  0.47739916]
 [ 1.94321462  2.18056084]
 [-0.15807423 -1.07893824]
 [-1.39974491 -1.46068138]
 [ 2.03872775  1.76945285]
 [-0.82666613 -0.78528968]
 [-0.82666613  0.38930459]
 [-0.73115301  1.35834485]
 [-0.25358736 -0.57973568]
 [ 0.89257019  1.09406114]
 [-1.11320552  0.41866944]
 [-0.92217926 -1.1083031 ]
 [-0.54012675  0.88850715]
 [ 1.46564897  0.35993973]
 [-1.49525804  0.33057487]
 [-1.78179743 -1.49004624]
 [-0.44461362 -1.13766796]
 [ 0.98808332 -1.02020853]
 [-0.25358736 -1.25512738]
 [ 0.89257019 -1.37258681]
 [ 0.51051768  1.74008799]
 [-1.6862843  -0.99084367]
 [ 0.12846516  0.15438573]
 [ 0.03295203 -0.57973568]
 [-0.63563988  0.12502088]
 [-0.34910049 -0.78528968]
 [-0.15807423  1.41707457]
 [ 1.37013584 -1.43131652]
 [-0.25358736 -1.37258681]
 [-0.82666613 -0.25672226]
 [ 0.89257019 -1.3138571 ]
 [-0.25358736  0.53612887]
 [ 0.98808332  1.7988177 ]
 [-0.63563988 -1.51941109]
 [-1.39974491 -0.10989798]
 [-0.63563988  0.56549373]
 [-1.6862843  -1.37258681]
 [-1.20871865 -1.07893824]
 [ 0.70154394 -1.40195167]
 [ 0.79705706 -1.37258681]
 [-1.59077117 -1.5781408 ]
 [ 0.31949142 -1.16703281]
 [ 0.79705706 -1.1083031 ]
 [-0.0625611  -0.4329114 ]
 [ 1.08359645  0.56549373]
 [-1.11320552  1.41707457]
 [ 0.89257019  2.18056084]
 [-1.11320552  0.47739916]
 [ 0.89257019 -0.60910054]
 [ 0.12846516 -0.81465453]
 [-0.92217926 -0.75592482]
 [-0.73115301 -0.2273574 ]
 [-0.92217926  0.4480343 ]
 [-0.63563988 -1.04957339]
 [-0.34910049  1.32898   ]
 [ 0.12846516  0.03692631]
 [ 1.94321462  0.917872  ]
 [ 0.22397829  0.15438573]
 [ 0.89257019  1.03533143]
 [ 1.27462271 -1.37258681]
 [ 1.08359645 -0.13926283]
 [ 0.98808332 -1.16703281]
 [-0.25358736  0.27184516]
 [-0.25358736 -0.9027491 ]
 [-1.49525804 -1.25512738]
 [ 1.94321462 -0.93211396]
 [-0.82666613 -1.22576253]
 [ 0.31949142 -0.31545197]
 [-0.73115301  0.50676401]
 [-0.44461362  2.32738512]
 [ 0.89257019 -0.57973568]
 [ 0.31949142 -0.28608712]
 [ 0.70154394 -1.40195167]
 [ 0.03295203 -0.25672226]
 [ 0.70154394 -1.1083031 ]
 [-1.11320552  0.06629116]
 [-0.15807423  0.15438573]
 [-0.63563988  1.41707457]
 [ 0.79705706 -0.84401939]
 [-1.30423178  0.56549373]
 [ 0.12846516  0.21311545]
 [-0.44461362 -0.78528968]
 [-0.82666613  0.30121002]
 [ 0.79705706 -1.40195167]
 [-1.01769239 -0.34481683]
 [ 0.31949142 -0.55037082]
 [ 0.31949142  0.30121002]
 [-1.01769239 -1.13766796]
 [-1.49525804 -1.51941109]
 [-0.73115301  1.91627713]
 [ 0.98808332  0.12502088]
 [ 0.89257019  1.27025028]
 [ 1.17910958 -0.75592482]
 [-0.92217926 -0.96147882]
 [ 0.79705706 -1.22576253]
 [-0.15807423 -0.28608712]
 [-0.44461362  1.27025028]
 [-0.54012675  1.38770971]
 [-0.0625611  -0.37418169]
 [-0.0625611  -0.49164111]
 [-1.11320552 -1.60750566]
 [-0.63563988  0.03692631]
 [ 1.08359645 -0.9027491 ]
 [ 2.03872775  2.15119598]
 [ 1.08359645  0.53612887]
 [ 0.41500455 -0.46227625]
 [ 1.65667523  1.76945285]
 [-0.25358736  0.15438573]
 [-1.01769239  0.56549373]
 [-0.0625611   0.15438573]
 [ 1.17910958 -0.99084367]
 [ 0.41500455  0.30121002]
 [-1.59077117 -0.05116826]
 [-1.6862843   0.12502088]
 [ 0.41500455 -0.16862769]
 [-0.15807423  0.85914229]
 [-0.25358736 -1.46068138]
 [ 0.22397829  0.06629116]
 [-0.15807423 -0.19799255]
 [-1.20871865 -1.40195167]
 [-0.25358736 -0.93211396]
 [-1.30423178 -1.49004624]
 [-0.25358736 -0.25672226]
 [-0.92217926  0.41866944]
 [-0.73115301  0.30121002]
 [ 0.89257019 -0.55037082]
 [ 0.31949142 -0.19799255]
 [ 1.08359645 -0.99084367]
 [ 0.03295203 -0.55037082]
 [ 0.79705706  0.35993973]
 [-0.0625611   0.21311545]
 [ 0.98808332 -1.19639767]
 [ 0.41500455 -0.49164111]
 [-1.30423178 -1.1083031 ]
 [-1.11320552  0.30121002]
 [ 0.22397829 -0.66783025]
 [-0.63563988 -0.34481683]
 [-1.20871865  0.27184516]
 [ 1.75218836  1.85754742]
 [ 2.03872775  0.38930459]
 [ 0.22397829  0.2424803 ]
 [-0.44461362 -0.02180341]
 [-1.78179743  0.4480343 ]
 [-0.92217926 -0.4329114 ]
 [-1.20871865  0.59485858]
 [ 1.27462271  1.88691227]
 [ 0.22397829 -0.25672226]
 [ 0.31949142  0.50676401]
 [-0.25358736 -1.40195167]
 [ 1.46564897  1.00596657]
 [ 0.41500455  2.32738512]
 [ 0.12846516 -0.25672226]
 [-1.11320552 -0.52100597]
 [-1.39974491 -0.19799255]
 [ 1.37013584  1.29961514]
 [ 0.89257019 -0.78528968]
 [ 1.75218836  1.00596657]
 [-0.25358736  0.03692631]
 [-1.11320552 -0.78528968]
 [-1.59077117  0.53612887]
 [-1.87731056 -0.52100597]
 [-1.39974491  0.35993973]
 [ 0.03295203  0.03692631]
 [-1.11320552 -1.02020853]
 [-0.0625611   0.03692631]
 [-1.01769239  1.97500684]
 [ 0.41500455 -0.13926283]
 [ 1.46564897  2.15119598]
 [-0.0625611  -0.2273574 ]
 [-0.25358736 -1.3138571 ]
 [-0.54012675 -1.51941109]
 [-0.82666613 -0.66783025]
 [-0.44461362 -1.22576253]
 [-1.6862843   0.47739916]
 [-0.25358736  0.15438573]
 [-1.01769239  0.53612887]
 [-1.87731056 -0.75592482]
 [ 0.98808332  0.77104772]
 [-0.0625611   1.97500684]
 [-1.30423178 -0.34481683]
 [-1.30423178 -0.4329114 ]
 [ 2.13424088  0.38930459]
 [-0.63563988  0.18375059]
 [-1.01769239 -1.46068138]
 [ 2.03872775 -0.81465453]
 [-0.34910049 -0.78528968]
 [ 0.41500455  0.15438573]
 [-0.92217926  1.56389885]
 [ 0.41500455  0.00756145]
 [ 0.98808332  2.0043717 ]
 [-0.0625611   0.68295315]
 [ 0.03295203 -0.13926283]
 [ 0.79705706  1.38770971]
 [-1.01769239  0.77104772]
 [-1.49525804 -0.19799255]
 [-0.73115301 -0.60910054]
 [-1.30423178 -0.4329114 ]
 [-1.6862843   0.35993973]
 [-1.78179743 -1.3138571 ]
 [-0.82666613  2.29802026]
 [-1.11320552  0.33057487]
 [-1.78179743  0.00756145]
 [-0.25358736  0.80041258]
 [-0.73115301  0.56549373]
 [-0.92217926  0.56549373]
 [ 0.98808332  2.09246627]
 [-0.73115301  1.09406114]
 [-0.44461362 -0.55037082]
 [-0.15807423 -0.57973568]
 [ 0.98808332  1.88691227]
 [ 1.27462271  2.23929055]
 [-0.92217926 -0.31545197]
 [ 0.12846516  0.27184516]
 [ 0.03295203 -0.57973568]
 [-0.92217926  0.27184516]
 [-0.63563988 -0.05116826]
 [ 1.17910958  0.53612887]
 [ 0.12846516  0.09565602]
 [ 0.22397829 -0.37418169]
 [ 0.41500455 -0.13926283]
 [-1.30423178 -1.37258681]
 [ 0.31949142  0.06629116]
 [-0.44461362 -0.28608712]
 [-0.54012675  1.91627713]
 [ 0.51051768  1.85754742]
 [ 0.12846516  0.77104772]
 [ 1.37013584  2.0043717 ]
 [ 2.13424088  1.123426  ]
 [ 1.08359645  0.47739916]
 [ 0.22397829 -0.13926283]
 [-0.63563988 -1.60750566]
 [ 1.08359645  0.12502088]
 [-1.01769239 -0.34481683]
 [-0.25358736 -0.28608712]
 [-0.82666613  0.38930459]
 [ 0.31949142 -0.72655996]
 [-0.25358736  0.06629116]
 [ 0.41500455  1.123426  ]
 [-0.25358736 -0.37418169]
 [ 0.03295203  0.03692631]
 [ 1.17910958 -1.46068138]
 [ 1.75218836 -0.28608712]
 [ 0.22397829 -0.28608712]
 [ 0.31949142  0.06629116]
 [ 1.84770149  0.12502088]
 [-0.25358736 -0.66783025]
 [-0.25358736 -0.57973568]
 [-1.6862843   0.35993973]
 [ 1.65667523 -0.9027491 ]
 [-1.11320552 -1.16703281]
 [-1.11320552 -1.1083031 ]
 [-0.25358736 -0.49164111]
 [ 1.5611621   1.00596657]
 [ 0.70154394  0.27184516]
 [-1.6862843  -0.60910054]
 [ 0.41500455  0.09565602]
 [ 0.12846516  1.06469629]
 [ 0.41500455  0.30121002]
 [-0.25358736 -0.34481683]
 [ 0.03295203  1.24088543]
 [-0.92217926 -0.31545197]
 [-0.92217926  0.50676401]
 [ 1.08359645 -1.22576253]
 [ 2.03872775 -1.19639767]
 [ 0.98808332  0.59485858]
 [ 0.41500455  1.00596657]
 [ 0.89257019 -1.16703281]
 [-1.78179743  0.18375059]
 [-0.25358736 -0.31545197]
 [ 0.98808332 -0.84401939]
 [-1.11320552 -1.5781408 ]
 [-1.20871865  0.30121002]
 [-1.01769239 -0.37418169]
 [-0.25358736  1.123426  ]
 [-0.0625611   0.2424803 ]
 [ 0.03295203 -0.25672226]
 [ 2.03872775  0.53612887]
 [ 1.84770149 -0.28608712]
 [-1.78179743 -1.28449224]
 [ 0.79705706  0.12502088]
 [ 0.98808332 -1.07893824]
 [-0.34910049  1.24088543]
 [-0.44461362 -0.84401939]
 [-1.11320552 -1.54877595]
 [ 0.41500455  0.27184516]
 [ 0.98808332 -1.07893824]
 [-0.73115301 -1.60750566]
 [ 0.31949142 -0.52100597]
 [ 0.70154394  1.7988177 ]
 [ 1.84770149 -1.28449224]
 [ 0.12846516 -0.31545197]
 [ 1.65667523  1.62262856]
 [ 0.22397829  0.15438573]
 [ 0.31949142  0.27184516]
 [ 1.94321462 -0.66783025]
 [ 0.12846516  1.53453399]
 [-0.25358736 -0.4329114 ]
 [ 0.31949142  0.03692631]
 [ 0.12846516  1.88691227]
 [ 0.89257019 -1.46068138]
 [-1.87731056 -0.05116826]
 [ 0.89257019 -1.04957339]
 [-1.01769239  0.41866944]
 [ 1.37013584  0.59485858]
 [-0.25358736  0.06629116]
 [ 0.31949142  0.06629116]
 [-1.59077117  0.06629116]
 [-0.34910049 -1.3138571 ]
 [-1.30423178  0.41866944]
 [ 1.84770149 -1.07893824]
 [-0.25358736  2.26865541]
 [-0.0625611   2.23929055]
 [ 2.13424088 -0.81465453]
 [-0.0625611  -0.52100597]
 [-0.0625611   0.00756145]
 [-1.01769239 -1.54877595]
 [ 0.22397829 -0.31545197]
 [-0.0625611  -1.07893824]
 [-1.30423178 -1.25512738]
 [ 1.37013584 -0.93211396]
 [ 0.98808332  1.44643942]
 [ 2.13424088 -0.81465453]
 [ 0.79705706  0.77104772]
 [ 2.13424088  0.94723686]
 [ 2.03872775  0.18375059]
 [ 2.13424088 -1.04957339]]

In [7]:
from sklearn.neighbors import KNeighborsClassifier
cla=KNeighborsClassifier(n_neighbors=5,metric = 'minkowski', p = 2)
cla.fit(X_train,Y_train)

C:\Users\Sahil\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
y_pred = cla.predict(X_test)
print(y_pred)

[0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0
 0 1 1]

In [9]:
from sklearn.metrics import confusion_matrix
cnf=confusion_matrix(Y_test,y_pred)
print(cnf)

[[24  2]
 [ 3 11]]